### PR TITLE
feat: add code of conduct

### LINKED ISSUE #10: Link Code of Conduct
@patricia-gallardo I noticed that the page has no Code of Conduct and then I found https://github.com/tech-women/code-of-conduct ... I propose to adapt this code of conduct.

It's especially important to provide contact information during the event, so we need to add/replace: 

- [ ] a phone number, an email, a Slack channel which is monitored during the event
- [ ] either individuals or a group of people (e.g. "the organizers, who wear a yellow t-shirt") who can be approached in case of Code of Conduct violations

### PR DESCRIPTION
**Pull request by coderbyheart**
I've adapted the Code of Conducted for use at Tech Women Norway events.

I added you @patricia-gallardo as the main point of contact (in addition with the techwomen.no@gmail.com email / the contact form).

One thing that might need to be adapted is how to identify staff members during the event: 
> "Conference staff will be wearing "_Tech Women Norway_" t-shirts." 

[source](https://github.com/tech-women/tech-women.github.io/compare/code-of-conduct?expand=1#diff-7ad14a8fd9f9637d3c07a09a5148e2f0R45)

Fixes #10

### CODE REVIEW

**Comment by patricia-gallardo** [comment]
Great! Thank you! I can try to order up some t-shirts!

**Comment by patricia-gallardo** [comment]
I get a 404 on https://techwomen.no/code-of-conduct/ (I'm in the middle of teaching a workshop so I can't debug :sweat: :rofl: )

**Comment by coderbyheart** [comment]
GitHub only renders this without a slash: https://techwomen.no/code-of-conduct
while the local jekyll does serve it with a slash (and redirects the non-slash version to the slash version).
I've fixed that in 7682b9c7b7bebab4491fd5a46b11022f1bdc38b3

**Comment by patricia-gallardo** [comment]
That looks fantastic, thank you!

**Pull request merged**
